"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Operator = void 0;
var DataType;
(function (DataType) {
    DataType["ID"] = "ID";
    DataType["ARRAY"] = "ARRAY";
    DataType["STRING"] = "STRING";
    DataType["BOOLEAN"] = "BOOLEAN";
    DataType["INTEGER"] = "INTEGER";
    DataType["DOUBLE"] = "DOUBLE";
    DataType["DYNAMICLIST"] = "LIST";
    DataType["CHARACTER"] = "CHARACTER";
})(DataType || (DataType = {}));
var Operator;
(function (Operator) {
    Operator["PLUS"] = "+";
    Operator["MINUSMINUS"] = "--";
    Operator["PLUSPLUS"] = "++";
    Operator["MINUS"] = "-";
    Operator["NEGATION"] = "-*";
    Operator["DIVISION"] = "/";
    Operator["TIMES"] = "*";
    Operator["MODULE"] = "%";
    Operator["POWER"] = "^";
    Operator["TERNARY"] = "?:";
    Operator["EQUALSEQUALS"] = "==";
    Operator["MOREOREQUALS"] = ">=";
    Operator["MAJOR"] = ">";
    Operator["LESSOREQUALS"] = "<=";
    Operator["MINOR"] = "<";
    Operator["NOT"] = "!";
    Operator["NONEQUALS"] = "!=";
    Operator["AND"] = "&&";
    Operator["OR"] = "||";
})(Operator = exports.Operator || (exports.Operator = {}));
exports.default = DataType;
